name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Test-Taiga-Website:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./TaigaTests
    - name: Build
      run: dotnet build ./TaigaTests --no-restore
    - name: Test
      run: dotnet test ./TaigaTests --filter:'Category=Website' --no-build --verbosity normal
